FROM python:3.11.9-slim-bookworm

WORKDIR /app

# Установка зависимостей
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Копирование общего кода и файлов
COPY common/ /app/common/
COPY main.py /app/
COPY start.sh /app/
COPY wait_for_db.py /app/

# Делаем скрипты исполняемыми
RUN chmod +x /app/start.sh
RUN chmod +x /app/wait_for_db.py
# Точка входа будет использовать скрипт запуска
CMD ["/app/start.sh"]
